### PR TITLE
WIP implementation of caching

### PR DESCRIPTION
**Pull request by mac-chaffee**
Doesn't compile yet, just showing the work in progress for #149

This is a "minimal diff" version that doesn't cache everything but at least introduces some caching. I think some refactoring is required to fully cache all the expensive-but-cachable stuff.

I basically moved three DB queries, the GetBucket call, and the parsing of _redirects and _headers into `populateCache` mostly unmodified. The last DB query may require refactoring all callers of `AnalyticsVisitFromRequest`.

This PR is also based on the changes in #150 so there's duplicate diffing happening.

### CODE REVIEW

**Comment by neurosnap** [comment]
Overall looks good to me!  Nothing to comment here, I like the general approach.

**Comment by mac-chaffee** [comment]
@neurosnap Hmm I think it's dawning on me now that using an in-process cache may not work because `pgs/web` and `pgs/ssh` are two separate processes. So I can't easily tell `pgs/web` to clear the cache when something happens in `pgs/ssh`, like a new _headers file being uploaded or a project being deleted.

Any preferences for what to do about that? Deploying an out-of-process cache like redis feels a little silly for avoiding DB queries since postgres's in-memory caching for reads are comparable to redis's read performance: https://www.cybertec-postgresql.com/en/postgresql-vs-redis-vs-memcached-performance/

Perhaps I should wait to see how enabling DNS caching affects things before proceeding. Some timing info from production would be helpful for knowing where to focus after that.

**Comment by mac-chaffee** [comment]
Another option could be something like https://github.com/caddyserver/cache-handler to just cache response bodies. It apparently has an API that can be used to clear the cache, which in theory could be called from `pgs/ssh`.

**Comment by neurosnap** [comment]
Oh, interesting!  I think it might be worth giving that caddy module a shot as it would move the responsibility of caching outside of our application code.  So long as we have the ability to purge the cache and it has the granularity we need.

Requirements:
- Ability to purge project cache
- Ability to purge user cache (optional but nice)
- Ability to purge entire cache

If you would find it useful, feel free to email us at hello@pico.sh or join our irc channel (#pico.sh) on libera.chat if you want more active pairing.

**Comment by mac-chaffee** [comment]
Moved the commit that limits file sizes to #153 and will close this since in-process caching is likely a dead end.

**Pull request closed without merging**
