### PR TITLE
refactor(pgs): use soiun in-app for http caching

### PR DESCRIPTION
**Pull request by neurosnap**
This gives us more control over the underlying cache and lets us build our own system for purging our cache.

### CODE REVIEW

**Comment by mac-chaffee** [comment]
Very clever I must say! I kicked the tires a little bit. 

We'd either need to expose Souin's internal API on pgs or wrap its methods for purging by surrogate key with pgs' own API, then be able to call that API from pgs-ssh.

There's definite risks, like probably being the only person on the planet using Souin in this way, but seems promising.

**Comment by neurosnap** [comment]
Overall I think this is going to be the winning approach for a couple of reasons:

- Souin is written in Go with a supported API for direct integration with our apps
- Easy to test and develop since it is inside our app
- We have direct access to the caching layer
- We can use our own systems for managing cache clearing API instead of relying on Souin's http api

I'm working on the cache clearing API and will let you review it when it's ready.  Thanks for all your help!

**Comment by neurosnap** [comment]
This has been deployed.  I'll be monitoring its status but custom domains should be properly cached now

**Comment by mac-chaffee** [comment]
Nice work using `pipe` for cache clearing! Glad we could settle on a solution that you'd be comfortable with!

Now I can rest easy knowing most visitors to my site are only waiting on latency and an in-memory lookup 😎

**Pull request closed without merging**
