### PR TITLE
chore(lists): shutdown notice on website

### PR DESCRIPTION
**Pull request by neurosnap**
Screenshot 2023-10-14 at 3 40 24 PM

### CODE REVIEW

**Comment by jchenry** [comment]
:-(

**Comment by neurosnap** [comment]
After talking with @antoniomika we are going to pause this for now.  We are thinking about merging lists.sh and prose.sh together but want to think through the ramifications

**Comment by jchenry** [comment]
@neurosnap @antoniomika might be worth while to implement it as a goldmark extension

**Comment by neurosnap** [comment]
Great idea!  We are definitely thinking about folding lists.sh into prose.sh since they are so similar, this could be one way to do it.

**Pull request closed without merging**
